(* generated by dune *)

(** @canonical Tensorlib.Scfloat32__OpAdd_Float32 *)
module Scfloat32__OpAdd_Float32 = Tensorlib__Scfloat32__OpAdd_Float32

(** @canonical Tensorlib.Scfloat32__ScalarFloat32 *)
module Scfloat32__ScalarFloat32 = Tensorlib__Scfloat32__ScalarFloat32

(** @canonical Tensorlib.Scint32__OpAdd_Int32 *)
module Scint32__OpAdd_Int32 = Tensorlib__Scint32__OpAdd_Int32

(** @canonical Tensorlib.Scint32__ScalarInt32 *)
module Scint32__ScalarInt32 = Tensorlib__Scint32__ScalarInt32

(** @canonical Tensorlib.Sequence__Seq *)
module Sequence__Seq = Tensorlib__Sequence__Seq

(** @canonical Tensorlib.Tensor *)
module Tensor = Tensorlib__Tensor

(** @canonical Tensorlib.Tensor__Index *)
module Tensor__Index = Tensorlib__Tensor__Index

(** @canonical Tensorlib.Tensor__Shape *)
module Tensor__Shape = Tensorlib__Tensor__Shape

(** @canonical Tensorlib.Tensor__Tensor *)
module Tensor__Tensor = Tensorlib__Tensor__Tensor
