(* generated by dune *)

(** @canonical Tensorlib.Opadd__Add *)
module Opadd__Add = Tensorlib__Opadd__Add

(** @canonical Tensorlib.Scalar__Scalar *)
module Scalar__Scalar = Tensorlib__Scalar__Scalar

(** @canonical Tensorlib.Sequence__Seq *)
module Sequence__Seq = Tensorlib__Sequence__Seq

(** @canonical Tensorlib.Tensor *)
module Tensor = Tensorlib__Tensor

(** @canonical Tensorlib.Tensor__Index *)
module Tensor__Index = Tensorlib__Tensor__Index

(** @canonical Tensorlib.Tensor__Shape *)
module Tensor__Shape = Tensorlib__Tensor__Shape

(** @canonical Tensorlib.Tensor__Tensor *)
module Tensor__Tensor = Tensorlib__Tensor__Tensor
